### ISSUE TITLE
Enhancing social buttons

### ISSUE THREAD

**Issue by mkemeter** [piazzai/cvless#16]
Hi! I just started to setup a page using this template and love it! 

I would like to have the possibility to add some more social buttons on the starting page. Namely, I deem the following platforms relevant:
* BlueSky
* Medium
* Xing
* Mastodon

Do you see a possibility of adding them or even of adding custom links via user configuration? Alternatively, are you open to pull requests? It seems like a new button, just needs enhancement [here](https://github.com/piazzai/cvless/blob/21cc8c367d50ea8eef84e2710328ef8f12cac6d1/_includes/particles-home.html) and the svg to be uploaded maybe [here](https://github.com/piazzai/cvless/tree/21cc8c367d50ea8eef84e2710328ef8f12cac6d1/_includes/svg)?

**Comment by piazzai** [comment]
Hi! I'm happy you like the template.

What you suggest is both useful and easy to implement. You also identified exactly what needs to be done to add new icons. The only problem is that the current icons are based on the [Iconoir](https://iconoir.com/) library, which is unfortunately a bit weak when it comes to brand icons. Mastodon is there, but Medium, Xing, and BlueSky are not.

It's probably best to use [Simple Icons](https://simpleicons.org/) instead of Iconoir, at least for social icons. Pull requests are more than welcome!

**Comment by piazzai** [comment]
The changes you made in #17 were viable, except that the icons didn't really work out because they had a different design than the rest, and it was impossible for me to make them look consistent. In the end, I noticed that Iconoir _does_ have a Medium icon, so for Medium and Mastodon I used the Iconoir design. For Bluesky and Xing, I used the Simple Icons version, but I customized it. Hopefully it's not too noticeable that they come from different icon packs.

I also made some changes to the code you added in `_includes/particles-home/`. In particular, profile urls on Medium look like _medium.com/@username_ ([source](https://help.medium.com/hc/en-us/articles/115004746707-Your-profile-page-URL)). Therefore, I added `@` to the fixed part of the url in `_includes/particles_home.html`. Profile urls on Bluesky normally look like _https://bsky.app/profile/username.bsky.social_. However, Bluesky allows users to use their own domain names in the handle ([source](https://bsky.social/about/blog/3-6-2023-domain-names-as-handles-in-bluesky)), so the user should set both the domain and the username in `_config.yml`. The same goes for Mastodon.

I included these changes, together with other things that were on my to-do list, in the new release (2.3.0). Please let me know if there is anything I missed.

**Comment by mkemeter** [comment]
Nice! Many thanks!

For Bluesky, you try to differentiate between username and domain, which doesn't really work neatly. My handle for example is [@kemeter.rocks](https://bsky.app/profile/kemeter.rocks) - so the handle is only my domain without what you name `username`. As you currently enforce at least on `.`, I need to use `username = kemeter` and `domain = rocks`.

**Comment by piazzai** [comment]
> Nice! Many thanks!
> 
> For Bluesky, you try to differentiate between username and domain, which doesn't really work neatly. My handle for example is [@kemeter.rocks](https://bsky.app/profile/kemeter.rocks) - so the handle is only my domain without what you name `username`. As you currently enforce at least on `.`, I need to use `username = kemeter` and `domain = rocks`.

Yes, that was my intention. But maybe it's not ideal. The more I think about it, the more I feel like allowing the user to just set the entire url in `_config.yml` is a better solution. So, in the config file you would write:

```yaml
bluesky: bsky.app/profile/kemeter.rocks
```

And in `_includes/particles-home.html` you would just leave the protocol:

```html
{% if site.social.bluesky %}
<a class="particles-icon" href="https://{{ site.social.bluesky }}">{% include svg/bluesky.svg %}</a>
{% endif %}
```

This would need to be done for every social icon. I'll get to it at some point, but if you want to make the pull request I'd be happy to merge it.

**Comment by piazzai** [comment]
Just FYI, the new release (v2.4.0) allows the user to specify the full url of social media profiles in `_config.yml`, as follows:

```yml
bluesky: https://bsky.app/profile/kemeter.rocks
```

The icon in `_includes/particles-home.html` uses that url in the href field:

```html
{% if site.social.bluesky %}
<a class="particles-icon" href="{{ site.profile.bluesky }}">{% include svg/bluesky.svg %}</a>
{% endif %}
```
