### ISSUE TITLE
Issue: /posts

### ISSUE THREAD

**Issue by necrux** [piazzai/cvless#2]
Any thoughts on why `/posts` is not showing any content after pushing to GitHub Pages? I can view the individual posts linked at the bottom of `About`, and `/posts` is rendering properly when running Jekyll locally. Thanks in advance!

**Comment by necrux** [comment]
It looks like `jekyll-paginate-v2` is not supported by GitHub Pages. I was able to workaround that by enabling a GitHub Action as opposed to the standard branch deploy.

**Comment by piazzai** [comment]
Thanks a lot for spotting this. Perhaps it was my mistake in the first place. In response to the other issue you opened (#1), I changed `_config.yml` and `Gemfile` in a way that could allow `jekyll-paginate-v2` to work correctly on GitHub Pages without the GitHub Action. If you could check again, I'd be really grateful. And if the problem persists, it'd be great if you could detail your Action-based solution so that I may add a note in the Readme.

**Comment by necrux** [comment]
I'll give it a try this afternoon. Here is the Action solution that I am using:

https://github.com/necrux/necrux.com/blob/main/.github/workflows/jekyll.yml
